include $(HOME)/common/env_proc_32.mk
include $(HOME)/common/env_uda.mk
LOCALFLAGS=-D_NDEBUG_ -D_UDA1_ -Aa -I$(HOME)/src/ACC/INCLUDE

EXE =  CAccMain  
OBJS = CAccMain.o Ctime.o CTime.o AccountUDR.o AccountGen.o dblib.o TPdsnInfo.o TMetaAction.o CSQLException.o $(UDALINKLIBES)

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(PROLDLIBS) $(UDALIBES) $(UDALINKLIBES) 

install : $(EXE)
	$(INSTALL2) $(EXE) $(COMMBINPATH)/
	rm -f $(EXE) *.o dblib.cpp TPdsnInfo.cpp TMetaAction.cpp CSQLException.cpp *.lis core 

clean :	
	rm -f $(EXE) *.o dblib.cpp TPdsnInfo.cpp TMetaAction.cpp CSQLException.cpp *.lis core 
	touch *.pc




