include /home/uda1/common/env_uda.mk

MFLAGS=-D_SVC1

EXE = readF
OBJS = RdUDRfile.o $(UDALINKLIBES)

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(PROLDLIBS) 

install : $(EXE)
	$(INSTALL2) $(UDALINKLIBES) $(COMMLIBPATH)
	rm -rf $(EXE) *.o core 

clean :	
	rm -rf $(EXE) *.o core 
	touch *.cpp




