include $(HOME)/common/env_proc_32.mk
include $(HOME)/common/env_uda.mk

#MFLAGS=-D_SVC1

EXE = dispcfg
OBJS = DisplayConfig.o $(UDALINKLIBES)

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(PROLDLIBS) $(UDALINKLIBES)

install : $(EXE)
	$(INSTALL2) $(EXE) $(PROJECTPATH)/util/
	rm -rf $(EXE) *.o core 

clean :	
	rm -rf $(EXE) *.o core 
	touch *.cpp




