include /home/uda/common/env_uda.mk

MFLAGS = -D_SVC1

EXE = tlog01
OBJS = tlog01.o $(UDALINKLIBES)

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(PROLDLIBS) $(UDALINKLIBES)

install : $(EXE)
	$(INSTALL2) $(UDALINKLIBES) $(COMMLIBPATH)
	rm -rf $(EXE) *.o core 

clean :	
	rm -rf $(EXE) *.o core 
	touch *.cpp




