include $(HOME)/src/SCP/lucent/ama/env_uda.mk

#MFLAGS=-D_SVC1

EXE = lucentif
OBJS = lucent_if.o  

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(PROLDLIBS) $(UDALINKLIBES) $(AMALINKLIBES) -lnsl -ldld

install : $(EXE)
	$(INSTALL2) $(EXE) $(COMMBINPATH)/
	rm -rf $(EXE) *.o core 

clean :	
	rm -rf $(EXE) *.o core 
	touch *.cpp
