include $(HOME)/common/env_proc_32.mk
include $(HOME)/common/env_uda.mk

MFLAGS=-D_SVC1
EXE = Obhst
OBJS = ObservHst.o 

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(PROLDLIBS) $(UDASQLLIBES) $(UDALINKLIBES)

install : $(EXE)
	$(INSTALL2) $(EXE) $(COMMBINPATH)/
	rm -rf $(EXE) *.o core 

clean :	
	rm -rf $(EXE) *.o *.cpp core 
	touch *.pc




