/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "amatps.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */
#include <signal.h>
#include <unistd.h> /* setsid */
#include <sys/types.h>
#include <memory.h>
#include <stropts.h>
#include <netconfig.h>
#include <sys/resource.h> /* rlimit */
#include <sys/fcntl.h> 
#include <syslog.h>

#ifndef SIG_PF
#define	SIG_PF void(*)(int)
#endif

#ifdef DEBUG
#define	RPC_SVC_FG
#endif

#define	_RPCSVC_CLOSEDOWN 120
static int _rpcpmstart;		/* Started by a port monitor ? */

/* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1

static int _rpcsvcstate = _IDLE;	/* Set when a request is serviced */
static int _rpcsvccount = 0;		/* Number of requests being serviced */

static
void _msgout(char* msg)
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

static void
closedown(int sig)
{
	if (_rpcsvcstate == _IDLE && _rpcsvccount == 0) {
		extern fd_set svc_fdset;
		static int size;
		int i, openfd;
		struct t_info tinfo;

		if (!t_getinfo(0, &tinfo) && (tinfo.servtype == T_CLTS))
			exit(0);
		if (size == 0) {
			struct rlimit rl;

			rl.rlim_max = 0;
			getrlimit(RLIMIT_NOFILE, &rl);
			if ((size = rl.rlim_max) == 0) {
				return;
			}
		}
		for (i = 0, openfd = 0; i < size && openfd < 2; i++)
			if (FD_ISSET(i, &svc_fdset))
				openfd++;
		if (openfd <= 1)
			exit(0);
	} else
		_rpcsvcstate = _IDLE;

	(void) signal(SIGALRM, (SIG_PF) closedown);
	(void) alarm(_RPCSVC_CLOSEDOWN/2);
}

static int *
_rpc_ack_primary_1(ack_input  *argp, struct svc_req *rqstp)
{
	return (rpc_ack_primary_1_svc(*argp, rqstp));
}

static int *
_rpc_connect_session_1(connect_input  *argp, struct svc_req *rqstp)
{
	return (rpc_connect_session_1_svc(*argp, rqstp));
}

static int *
_rpc_disconnect_session_1(disconnect_input  *argp, struct svc_req *rqstp)
{
	return (rpc_disconnect_session_1_svc(*argp, rqstp));
}

static primary_return *
_rpc_poll_primary_1(int  *argp, struct svc_req *rqstp)
{
	return (rpc_poll_primary_1_svc(*argp, rqstp));
}

static secondary_return *
_rpc_poll_secondary_1(secondary_input  *argp, struct svc_req *rqstp)
{
	return (rpc_poll_secondary_1_svc(*argp, rqstp));
}

static maint_return *
_rpc_poll_maint_1(int  *argp, struct svc_req *rqstp)
{
	return (rpc_poll_maint_1_svc(*argp, rqstp));
}

static int *
_rpc_ssend_1(ssend_input  *argp, struct svc_req *rqstp)
{
	return (rpc_ssend_1_svc(*argp, rqstp));
}

static srecv_return *
_rpc_srecv_1(srecv_input  *argp, struct svc_req *rqstp)
{
	return (rpc_srecv_1_svc(*argp, rqstp));
}

static int *
_rpc_test_connection_1(test_input  *argp, struct svc_req *rqstp)
{
	return (rpc_test_connection_1_svc(*argp, rqstp));
}

static int *
_rpc_set_trace_1(trace_input  *argp, struct svc_req *rqstp)
{
	return (rpc_set_trace_1_svc(*argp, rqstp));
}

static link_return *
_rpc_get_link_stats_1(int  *argp, struct svc_req *rqstp)
{
	return (rpc_get_link_stats_1_svc(*argp, rqstp));
}

static int *
_rpc_reset_link_stats_1(int  *argp, struct svc_req *rqstp)
{
	return (rpc_reset_link_stats_1_svc(*argp, rqstp));
}

static int *
_rpc_get_link_status_1(int  *argp, struct svc_req *rqstp)
{
	return (rpc_get_link_status_1_svc(*argp, rqstp));
}

static dcf_return *
_rpc_get_dcf_1(char * *argp, struct svc_req *rqstp)
{
	return (rpc_get_dcf_1_svc(*argp, rqstp));
}

static int *
_rpc_put_dcf_1(put_input  *argp, struct svc_req *rqstp)
{
	return (rpc_put_dcf_1_svc(*argp, rqstp));
}

static int *
_rpc_reset_server_1(char * *argp, struct svc_req *rqstp)
{
	return (rpc_reset_server_1_svc(*argp, rqstp));
}

static void
amatpsplus_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ack_input rpc_ack_primary_1_arg;
		connect_input rpc_connect_session_1_arg;
		disconnect_input rpc_disconnect_session_1_arg;
		int rpc_poll_primary_1_arg;
		secondary_input rpc_poll_secondary_1_arg;
		int rpc_poll_maint_1_arg;
		ssend_input rpc_ssend_1_arg;
		srecv_input rpc_srecv_1_arg;
		test_input rpc_test_connection_1_arg;
		trace_input rpc_set_trace_1_arg;
		int rpc_get_link_stats_1_arg;
		int rpc_reset_link_stats_1_arg;
		int rpc_get_link_status_1_arg;
		char *rpc_get_dcf_1_arg;
		put_input rpc_put_dcf_1_arg;
		char *rpc_reset_server_1_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	_rpcsvccount++;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp,
			(xdrproc_t) xdr_void, (char *)NULL);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;

	case rpc_ack_primary:
		xdr_argument = (xdrproc_t) xdr_ack_input;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_ack_primary_1;
		break;

	case rpc_connect_session:
		xdr_argument = (xdrproc_t) xdr_connect_input;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_connect_session_1;
		break;

	case rpc_disconnect_session:
		xdr_argument = (xdrproc_t) xdr_disconnect_input;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_disconnect_session_1;
		break;

	case rpc_poll_primary:
		xdr_argument = (xdrproc_t) xdr_int;
		xdr_result = (xdrproc_t) xdr_primary_return;
		local = (char *(*)(char *, struct svc_req *)) _rpc_poll_primary_1;
		break;

	case rpc_poll_secondary:
		xdr_argument = (xdrproc_t) xdr_secondary_input;
		xdr_result = (xdrproc_t) xdr_secondary_return;
		local = (char *(*)(char *, struct svc_req *)) _rpc_poll_secondary_1;
		break;

	case rpc_poll_maint:
		xdr_argument = (xdrproc_t) xdr_int;
		xdr_result = (xdrproc_t) xdr_maint_return;
		local = (char *(*)(char *, struct svc_req *)) _rpc_poll_maint_1;
		break;

	case rpc_ssend:
		xdr_argument = (xdrproc_t) xdr_ssend_input;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_ssend_1;
		break;

	case rpc_srecv:
		xdr_argument = (xdrproc_t) xdr_srecv_input;
		xdr_result = (xdrproc_t) xdr_srecv_return;
		local = (char *(*)(char *, struct svc_req *)) _rpc_srecv_1;
		break;

	case rpc_test_connection:
		xdr_argument = (xdrproc_t) xdr_test_input;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_test_connection_1;
		break;

	case rpc_set_trace:
		xdr_argument = (xdrproc_t) xdr_trace_input;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_set_trace_1;
		break;

	case rpc_get_link_stats:
		xdr_argument = (xdrproc_t) xdr_int;
		xdr_result = (xdrproc_t) xdr_link_return;
		local = (char *(*)(char *, struct svc_req *)) _rpc_get_link_stats_1;
		break;

	case rpc_reset_link_stats:
		xdr_argument = (xdrproc_t) xdr_int;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_reset_link_stats_1;
		break;

	case rpc_get_link_status:
		xdr_argument = (xdrproc_t) xdr_int;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_get_link_status_1;
		break;

	case rpc_get_dcf:
		xdr_argument = (xdrproc_t) xdr_wrapstring;
		xdr_result = (xdrproc_t) xdr_dcf_return;
		local = (char *(*)(char *, struct svc_req *)) _rpc_get_dcf_1;
		break;

	case rpc_put_dcf:
		xdr_argument = (xdrproc_t) xdr_put_input;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_put_dcf_1;
		break;

	case rpc_reset_server:
		xdr_argument = (xdrproc_t) xdr_wrapstring;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_reset_server_1;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	return;
}

main()
{
	pid_t pid;
	int i;

	(void) signal(SIGPIPE, SIG_IGN);

	/*
	 * If stdin looks like a XTI endpoint, we assume
	 * that we were started by a port monitor. If
	 * t_getstate fails with TBADF, this is not a
	 * XTI endpoint.
	 */
	if (t_getstate(0) != -1 || t_errno != TBADF) {
		char *netid;
		struct netconfig *nconf = NULL;
		SVCXPRT *transp;
		int pmclose;

		_rpcpmstart = 1;
		openlog("amatps", LOG_PID, LOG_DAEMON);

		if ((netid = getenv("NLSPROVIDER")) == NULL) {
		/* started from inetd */
			pmclose = 1;
		} else {
			if ((nconf = getnetconfigent(netid)) == NULL)
				_msgout("cannot get transport info");

			pmclose = (t_getstate(0) != T_DATAXFER);
		}
		if ((transp = svc_tli_create(0, nconf, NULL, 0, 0)) == NULL) {
			_msgout("cannot create server handle");
			exit(1);
		}
		if (nconf)
			freenetconfigent(nconf);
		if (!svc_reg(transp, AMATPSPLUS, AMATPSPLUSVER, amatpsplus_1, 0)) {
			_msgout("unable to register (AMATPSPLUS, AMATPSPLUSVER).");
			exit(1);
		}
		if (pmclose) {
			(void) signal(SIGALRM, (SIG_PF) closedown);
			(void) alarm(_RPCSVC_CLOSEDOWN/2);
		}
		svc_run();
		exit(1);
		/* NOTREACHED */
	}	else {
#ifndef RPC_SVC_FG
		int size;
		struct rlimit rl;
		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		rl.rlim_max = 0;
		getrlimit(RLIMIT_NOFILE, &rl);
		if ((size = rl.rlim_max) == 0)
			exit(1);
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/console", O_RDWR);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		setsid();
		openlog("amatps", LOG_PID, LOG_DAEMON);
#endif
	}
	if (!svc_create(amatpsplus_1, AMATPSPLUS, AMATPSPLUSVER, "netpath")) {
		_msgout("unable to create (AMATPSPLUS, AMATPSPLUSVER) for netpath.");
		exit(1);
	}

	svc_run();
	_msgout("svc_run returned");
	exit(1);
	/* NOTREACHED */
}
