/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "amatps.h"

bool_t
xdr_ack_input(register XDR *xdrs, ack_input *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->ack))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_connect_input(register XDR *xdrs, connect_input *objp)
{

	register long *buf;

	if (!xdr_string(xdrs, &objp->dcf, ~0))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->acparms.acparms_val, (u_int *) &objp->acparms.acparms_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_disconnect_input(register XDR *xdrs, disconnect_input *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_primary_return(register XDR *xdrs, primary_return *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scode))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->fb.fb_val, (u_int *) &objp->fb.fb_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_secondary_input(register XDR *xdrs, secondary_input *objp)
{

	register long *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->scid))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->tb))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->fb))
				return (FALSE);
			if (!xdr_long(xdrs, &objp->sbsn))
				return (FALSE);
			if (!xdr_long(xdrs, &objp->ebsn))
				return (FALSE);
		} else {
			IXDR_PUT_LONG(buf, objp->scid);
			IXDR_PUT_LONG(buf, objp->tb);
			IXDR_PUT_LONG(buf, objp->fb);
			IXDR_PUT_LONG(buf, objp->sbsn);
			IXDR_PUT_LONG(buf, objp->ebsn);
		}
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->scid))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->tb))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->fb))
				return (FALSE);
			if (!xdr_long(xdrs, &objp->sbsn))
				return (FALSE);
			if (!xdr_long(xdrs, &objp->ebsn))
				return (FALSE);
		} else {
			objp->scid = IXDR_GET_LONG(buf);
			objp->tb = IXDR_GET_LONG(buf);
			objp->fb = IXDR_GET_LONG(buf);
			objp->sbsn = IXDR_GET_LONG(buf);
			objp->ebsn = IXDR_GET_LONG(buf);
		}
		return (TRUE);
	}

	if (!xdr_int(xdrs, &objp->scid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->tb))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->fb))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->sbsn))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->ebsn))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_secondary_return(register XDR *xdrs, secondary_return *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scode))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->fb.fb_val, (u_int *) &objp->fb.fb_len, ~0))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->tb.tb_val, (u_int *) &objp->tb.tb_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_maint_return(register XDR *xdrs, maint_return *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scode))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->fb.fb_val, (u_int *) &objp->fb.fb_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ssend_input(register XDR *xdrs, ssend_input *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->mtype))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->smb.smb_val, (u_int *) &objp->smb.smb_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_srecv_input(register XDR *xdrs, srecv_input *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->mbsize))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_srecv_return(register XDR *xdrs, srecv_return *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scode))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->mtype))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->smb.smb_val, (u_int *) &objp->smb.smb_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_test_input(register XDR *xdrs, test_input *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_trace_input(register XDR *xdrs, trace_input *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->trace_class))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->trace_level))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->file_prefix, ~0))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->max_file_size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_link_return(register XDR *xdrs, link_return *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scode))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->x25_stat_buf.x25_stat_buf_val, (u_int *) &objp->x25_stat_buf.x25_stat_buf_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_dcf_return(register XDR *xdrs, dcf_return *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->scode))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fb, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_put_input(register XDR *xdrs, put_input *objp)
{

	register long *buf;

	if (!xdr_string(xdrs, &objp->dcf, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fb, ~0))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->cflag))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->password, ~0))
		return (FALSE);
	return (TRUE);
}
