
# This is a template makefile generated		by rpcgen 

# Parameters 
CC = cc
CLIENT = example
#SERVER = math_server

SOURCES_CLNT.c = example.c 
SOURCES_CLNT.h = 
#SOURCES_SVC.c = math_server.c 
#SOURCES_SVC.h = 
SOURCES.x = amatps.x

#TARGETS_SVC.c = math_svc.c math_xdr.c 
TARGETS_CLNT.c = amatps_clnt.c amatps_xdr.c client.c
#TARGETS = math.h math_xdr.c math_clnt.c math_svc.c 
TARGETS = amatps.h amatps_xdr.c amatps_clnt.c  

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o) 
#OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o) 
# Compiler flags 

#CFLAGS += -g 
#LDLIBS += -lnsl
CFLAGS = -g 
LDLIBS = -lnsl -ldld
MFLAGS = -D_hp
RPCGENFLAGS = -C -N

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

#$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(CC) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) $(MFLAGS)

#$(SERVER) : $(OBJECTS_SVC) 
#	$(CC) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) *~

