include /home/uda1/common/env_proc_32.mk
include /home/uda1/common/env_uda.mk

MFLAGS=-D_SVC1 -D_DEBUG
EXE = CLimitMain 
OBJS = CLimitMGR.o CLimitTbl.o RateRule.o $(UDASQLLIBES) $(UDALINKLIBES)
#OBJS = Aggregator.o

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(PROLDLIBS) $(UDASQLLIBES) $(UDALINKLIBES)

install : $(EXE)
	$(INSTALL2) $(EXE) $(COMMBINPATH)/
	rm -rf $(EXE) *.o core 

clean :	
	rm -rf $(EXE) *.o core CLimitTbl.cpp RateRule.cpp
	touch *.pc *.cpp




