include $(HOME)/common/env_proc_32.mk
include $(HOME)/common/env_uda.mk

MFLAGS=-D_SVC1
EXE = pfilter 
OBJS = filterC.o $(UDALINKLIBES)

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(PROLDLIBS) $(UDASQLLIBES) $(UDALINKLIBES) 

install : $(EXE)
	$(INSTALL2) $(EXE) $(COMMBINPATH)/
	rm -f $(EXE) *.o *.cpp core 

clean :	
	rm -f $(EXE) *.o *.cpp core 
	touch *.pc




