include /home/uda1/common/env_proc_32.mk
include /home/uda1/common/env_uda.mk
LOCALFLAGS=-I$(HOME)/src/MDB_TEST/INCLUDE

MFLAGS=-D_SVC1
EXE = testbtree
OBJS = test_btree3.o $(UDASQLLIBES) $(UDALINKLIBES)
#OBJS = Aggregator.o

all : $(EXE)

$(EXE) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(PROLDLIBS) $(UDASQLLIBES) $(UDALINKLIBES)

install : $(EXE)
	strip $(EXE)
	$(INSTALL2) $(EXE) $(COMMBINPATH)/
	rm -rf $(EXE) *.o core 

clean :	
	rm -rf $(EXE) *.o core 
	touch *.pc *.cpp




